[2025-07-30T15:37:51.548+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-30T15:37:51.561+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_json_to_doris.task_json_to_doris manual__2025-07-30T15:37:44.720496+00:00 [queued]>
[2025-07-30T15:37:51.566+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_json_to_doris.task_json_to_doris manual__2025-07-30T15:37:44.720496+00:00 [queued]>
[2025-07-30T15:37:51.566+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-07-30T15:37:51.591+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): task_json_to_doris> on 2025-07-30 15:37:44.720496+00:00
[2025-07-30T15:37:51.628+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_json_to_doris', 'task_json_to_doris', 'manual__2025-07-30T15:37:44.720496+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/dag_json_to_doris.py', '--cfg-path', '/tmp/tmpj7pfd_xw']
[2025-07-30T15:37:51.629+0000] {standard_task_runner.py:105} INFO - Job 176: Subtask task_json_to_doris
[2025-07-30T15:37:51.627+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=96) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-30T15:37:51.631+0000] {standard_task_runner.py:72} INFO - Started process 106 to run task
[2025-07-30T15:37:51.702+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_json_to_doris.task_json_to_doris manual__2025-07-30T15:37:44.720496+00:00 [running]> on host 7609641ebe00
[2025-07-30T15:37:51.793+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='reza' AIRFLOW_CTX_DAG_ID='dag_json_to_doris' AIRFLOW_CTX_TASK_ID='task_json_to_doris' AIRFLOW_CTX_EXECUTION_DATE='2025-07-30T15:37:44.720496+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-30T15:37:44.720496+00:00'
[2025-07-30T15:37:51.794+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-07-30T15:37:51.794+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-07-30T15:37:51.795+0000] {logging_mixin.py:190} INFO - Current task name:task_json_to_doris state:running start_date:2025-07-30 15:37:51.561397+00:00
[2025-07-30T15:37:51.795+0000] {logging_mixin.py:190} INFO - Dag name:dag_json_to_doris and current dag run status:running
[2025-07-30T15:37:51.795+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-30T15:37:51.797+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-30T15:37:51.801+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sh /opt/***/dags/script/json_to_raw.sh ']
[2025-07-30T15:37:51.822+0000] {subprocess.py:86} INFO - Output:
[2025-07-30T15:37:51.850+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2025-07-30T15:37:51.851+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2025-07-30T15:37:51.851+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2025-07-30T15:37:51.852+0000] {subprocess.py:93} INFO - curl: (7) Failed to connect to localhost port 8040 after 1 ms: Couldn't connect to server
[2025-07-30T15:37:51.862+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2025-07-30T15:37:51.863+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2025-07-30T15:37:51.863+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2025-07-30T15:37:51.863+0000] {subprocess.py:93} INFO - curl: (7) Failed to connect to localhost port 8040 after 0 ms: Couldn't connect to server
[2025-07-30T15:37:51.869+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2025-07-30T15:37:51.869+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2025-07-30T15:37:51.869+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2025-07-30T15:37:51.869+0000] {subprocess.py:93} INFO - curl: (7) Failed to connect to localhost port 8040 after 0 ms: Couldn't connect to server
[2025-07-30T15:37:51.874+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2025-07-30T15:37:51.874+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2025-07-30T15:37:51.874+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2025-07-30T15:37:51.874+0000] {subprocess.py:93} INFO - curl: (7) Failed to connect to localhost port 8040 after 0 ms: Couldn't connect to server
[2025-07-30T15:37:51.883+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2025-07-30T15:37:51.883+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2025-07-30T15:37:51.883+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2025-07-30T15:37:51.884+0000] {subprocess.py:93} INFO - curl: (7) Failed to connect to localhost port 8040 after 0 ms: Couldn't connect to server
[2025-07-30T15:37:51.885+0000] {subprocess.py:97} INFO - Command exited with return code 7
[2025-07-30T15:37:51.906+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 7.
[2025-07-30T15:37:51.919+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-07-30T15:37:51.919+0000] {logging_mixin.py:190} INFO - Task start:2025-07-30 15:37:51.561397+00:00 end:2025-07-30 15:37:51.918800+00:00 duration:0.357403
[2025-07-30T15:37:51.919+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): task_json_to_doris> dag:<DAG: dag_json_to_doris> dagrun:<DagRun dag_json_to_doris @ 2025-07-30 15:37:44.720496+00:00: manual__2025-07-30T15:37:44.720496+00:00, state:running, queued_at: 2025-07-30 15:37:44.747444+00:00. externally triggered: True>
[2025-07-30T15:37:51.920+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 7.
[2025-07-30T15:37:51.920+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_json_to_doris, task_id=task_json_to_doris, run_id=manual__2025-07-30T15:37:44.720496+00:00, execution_date=20250730T153744, start_date=20250730T153751, end_date=20250730T153751
[2025-07-30T15:37:51.928+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-30T15:37:51.929+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 176 for task task_json_to_doris (Bash command failed. The command returned a non-zero exit code 7.; 106)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 7.
[2025-07-30T15:37:51.944+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-30T15:37:51.961+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-30T15:37:51.961+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
