[2025-07-30T16:35:15.839+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-30T16:35:15.860+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_raw_to_refined.read_sql_coingecko_flat manual__2025-07-30T16:30:06.592508+00:00 [queued]>
[2025-07-30T16:35:15.869+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_raw_to_refined.read_sql_coingecko_flat manual__2025-07-30T16:30:06.592508+00:00 [queued]>
[2025-07-30T16:35:15.869+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-07-30T16:35:15.887+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): read_sql_coingecko_flat> on 2025-07-30 16:30:06.592508+00:00
[2025-07-30T16:35:15.896+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=876) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-30T16:35:15.898+0000] {standard_task_runner.py:72} INFO - Started process 878 to run task
[2025-07-30T16:35:15.899+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_raw_to_refined', 'read_sql_coingecko_flat', 'manual__2025-07-30T16:30:06.592508+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/dag_raw_to_refined.py', '--cfg-path', '/tmp/tmp5q7y2t5m']
[2025-07-30T16:35:15.901+0000] {standard_task_runner.py:105} INFO - Job 194: Subtask read_sql_coingecko_flat
[2025-07-30T16:35:15.952+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_raw_to_refined.read_sql_coingecko_flat manual__2025-07-30T16:30:06.592508+00:00 [running]> on host 7609641ebe00
[2025-07-30T16:35:15.999+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='reza' AIRFLOW_CTX_DAG_ID='dag_raw_to_refined' AIRFLOW_CTX_TASK_ID='read_sql_coingecko_flat' AIRFLOW_CTX_EXECUTION_DATE='2025-07-30T16:30:06.592508+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-30T16:30:06.592508+00:00'
[2025-07-30T16:35:16.003+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-07-30T16:35:16.003+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-07-30T16:35:16.003+0000] {logging_mixin.py:190} INFO - Current task name:read_sql_coingecko_flat state:running start_date:2025-07-30 16:35:15.861037+00:00
[2025-07-30T16:35:16.003+0000] {logging_mixin.py:190} INFO - Dag name:dag_raw_to_refined and current dag run status:running
[2025-07-30T16:35:16.004+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-30T16:35:16.008+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_raw_to_refined.py", line 22, in read_sql_file
    with open(sql_file, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/sql/silver/table_coingecko_flat.sql'
[2025-07-30T16:35:16.015+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-07-30T16:35:16.016+0000] {logging_mixin.py:190} INFO - Task start:2025-07-30 16:35:15.861037+00:00 end:2025-07-30 16:35:16.015110+00:00 duration:0.154073
[2025-07-30T16:35:16.016+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): read_sql_coingecko_flat> dag:<DAG: dag_raw_to_refined> dagrun:<DagRun dag_raw_to_refined @ 2025-07-30 16:30:06.592508+00:00: manual__2025-07-30T16:30:06.592508+00:00, state:running, queued_at: 2025-07-30 16:30:06.729542+00:00. externally triggered: True>
[2025-07-30T16:35:16.016+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/opt/***/dags/sql/silver/table_coingecko_flat.sql'
[2025-07-30T16:35:16.017+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_raw_to_refined, task_id=read_sql_coingecko_flat, run_id=manual__2025-07-30T16:30:06.592508+00:00, execution_date=20250730T163006, start_date=20250730T163515, end_date=20250730T163516
[2025-07-30T16:35:16.024+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-30T16:35:16.024+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 194 for task read_sql_coingecko_flat ([Errno 2] No such file or directory: '/opt/airflow/dags/sql/silver/table_coingecko_flat.sql'; 878)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_raw_to_refined.py", line 22, in read_sql_file
    with open(sql_file, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/sql/silver/table_coingecko_flat.sql'
[2025-07-30T16:35:16.044+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-30T16:35:16.056+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-30T16:35:16.058+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
